name: Deploy to Ubuntu Server (Dev)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /root/iwtDashboard/

            rm -rf IOTADashboard
            git clone https://github.com/jaffe9/IOTADashboard.git
            cd IOTADashboard

            git checkout dev
            git pull origin dev

            npm install
            npm run build

            pm2 restart appDashboard || pm2 start npm --name appDashboard -- run start
          EOF
